WITH city_info AS (
    SELECT p.state, p.start_year, p.title_22_ai, p.desc_22_ai, p.desc_25_ai, p.title_25_ai,
    CASE 
        WHEN regexp_like(p.location, 'San Francisco|\bSF[a-z]\b') THEN 'San Francisco'
        WHEN regexp_like(p.location, 'Seattle') THEN 'Seattle'
        WHEN regexp_like(p.location, 'New York City|\bNYC[a-z]\b') THEN 'New York City'
        WHEN regexp_like(p.location, 'Chicago') THEN 'Chicago'
        WHEN regexp_like(p.location, 'Houston') THEN 'Houston'
        WHEN (regexp_like(p.location, 'Los Angeles') AND p.state = 'CA') THEN 'Los Angeles'
        WHEN regexp_like(p.location, 'Phoenix') THEN 'Phoenix'
        WHEN regexp_like(p.location, 'Philadelphia') THEN 'Philadelphia'
        WHEN regexp_like(p.location, 'San Antonio') THEN 'San Antonio'
        WHEN regexp_like(p.location, 'San Diego') THEN 'San Diego'
        WHEN regexp_like(p.location, 'Dallas') THEN 'Dallas'
        WHEN regexp_like(p.location, 'Jacksonville') THEN 'Jacksonville'
        WHEN regexp_like(p.location, 'Austin') THEN 'Austin'
        WHEN regexp_like(p.location, 'San Jose') THEN 'San Jose'
        WHEN regexp_like(p.location, 'Columbus') THEN 'Columbus'
        WHEN (regexp_like(p.location, 'Charlotte') AND p.state = 'NC') THEN 'Charlotte'
        WHEN regexp_like(p.location, 'Indianapolis') THEN 'Indianapolis'
        WHEN regexp_like(p.location, 'Denver') THEN 'Denver'
        WHEN regexp_like(p.location, 'Oklahoma City') THEN 'Oklahoma City'
        WHEN (regexp_like(p.location, 'Nashville') AND p.state = 'TN') THEN 'Nashville'
        WHEN (regexp_like(p.location, 'DC') AND p.state = 'DC') THEN 'DC'
        WHEN regexp_like(p.location, 'El Paso') THEN 'El Paso'
        WHEN regexp_like(p.location, 'Las Vegas') THEN 'Las vegas'
        WHEN regexp_like(p.location, 'Boston') THEN 'Boston'
        WHEN regexp_like(p.location, 'Detroit') THEN 'Detroit'
        WHEN (regexp_like(p.location, 'Portland') AND p.state = 'OR') THEN 'Portland'
        WHEN regexp_like(p.location, 'Louisville') THEN 'Louisville'
        WHEN regexp_like(p.location, 'Memphis') THEN 'Memphis'
        WHEN regexp_like(p.location, 'Baltimore') THEN 'Baltimore'
        WHEN regexp_like(p.location, 'Milwaukee') THEN 'Milwaukee'
        WHEN regexp_like(p.location, 'Albuquerque') THEN 'Albuquerque'
        WHEN regexp_like(p.location, 'Tucson') THEN 'Tucson'
        WHEN regexp_like(p.location, 'Fresno') THEN 'Fresno'
        WHEN regexp_like(p.location, 'Sacramento') THEN 'Sacramento'
        WHEN (regexp_like(p.location, 'Mesa') AND p.state = 'AZ') THEN 'Mesa'
        WHEN regexp_like(p.location, 'Atlanta') THEN 'Atlanta'
        WHEN regexp_like(p.location, 'Kansas City') THEN 'Kansas City'
        WHEN regexp_like(p.location, 'Colorado Springs') THEN 'Colorado Springs'
        WHEN regexp_like(p.location, 'Omaha') THEN 'Omaha'
        WHEN regexp_like(p.location, 'Raleigh') THEN 'Raleigh'
        WHEN regexp_like(p.location, 'Miami') THEN 'Miami'
        WHEN regexp_like(p.location, 'Virginia Beach') THEN 'Virginia Beach'
        WHEN regexp_like(p.location, 'Long Beach') THEN 'Long Beach'
        WHEN regexp_like(p.location, 'Oakland') THEN 'Oakland'
        WHEN regexp_like(p.location, 'Minneapolis') THEN 'Minneapolis'
        WHEN regexp_like(p.location, 'Bakersfield') THEN 'Bakersfield'
        WHEN regexp_like(p.location, 'Tulsa') THEN 'Tulsa'
        WHEN (regexp_like(p.location, 'Tampa') AND p.state = 'FL') THEN 'Tampa'
        WHEN (regexp_like(p.location, 'Arlington') AND p.state = 'TX') THEN 'Arlington'
        WHEN regexp_like(p.location, 'Wichita') THEN 'Wichita'
        WHEN regexp_like(p.location, 'Aurora') THEN 'Aurora'
        WHEN regexp_like(p.location, 'New Orleans') THEN 'New Orleans'
        WHEN regexp_like(p.location, 'Cleveland') THEN 'Cleveland'
        WHEN regexp_like(p.location, 'Honolulu') THEN 'Honolulu'
        WHEN regexp_like(p.location, 'Anaheim') THEN 'Anaheim'
        WHEN regexp_like(p.location, 'Henderson') THEN 'Henderson'
        WHEN regexp_like(p.location, 'Orlando') THEN 'Orlando'
        WHEN (regexp_like(p.location, 'Lexington') AND p.state = 'KY') THEN 'Lexington'
        WHEN regexp_like(p.location, 'Riverside') THEN 'Riverside'
        WHEN regexp_like(p.location, 'Corpus Christi') THEN 'Corpus Christi'
        WHEN regexp_like(p.location, 'Irvine') THEN 'Irvine'
        WHEN regexp_like(p.location, 'Cincinnati') THEN 'Cincinnati'
        WHEN regexp_like(p.location, 'Santa Ana') THEN 'Santa Ana'
        WHEN regexp_like(p.location, 'Newark') THEN 'Newark'
        WHEN regexp_like(p.location, 'St. Paul') THEN 'St. Paul'
        WHEN regexp_like(p.location, 'Pittsburgh') THEN 'Pittsburgh'
        WHEN regexp_like(p.location, 'Greensboro') THEN 'Greensboro'
        WHEN regexp_like(p.location, 'Lincoln') THEN 'Lincoln'
        WHEN regexp_like(p.location, 'Jersey City') THEN 'Jersey City'
        WHEN regexp_like(p.location, 'Plano') THEN 'Plano'
        WHEN regexp_like(p.location, 'Anchorage') THEN 'Anchorage'
        WHEN regexp_like(p.location, 'North Las Vegas') THEN 'North Las Vegas'
        WHEN regexp_like(p.location, 'St. Louis') THEN 'St. Louis'
        WHEN (regexp_like(p.location, 'Madison') AND p.state = 'WI') THEN 'Madison'
        WHEN regexp_like(p.location, 'Chandler') THEN 'Chandler'
        WHEN regexp_like(p.location, 'Gilbert') THEN 'Gilbert'
        WHEN regexp_like(p.location, 'Reno') THEN 'Reno'
        WHEN regexp_like(p.location, 'Buffalo') THEN 'Buffalo'
        WHEN regexp_like(p.location, 'Chula Vista') THEN 'Chula Vista'
        WHEN regexp_like(p.location, 'Fort Wayne') THEN 'Fort Wayne'
        WHEN regexp_like(p.location, 'Toledo') THEN 'Toledo'
        WHEN (regexp_like(p.location, 'St. Petersburgh') AND p.state = 'FL') THEN 'St. Petersburgh'
        WHEN regexp_like(p.location, 'Laredo') THEN 'Laredo'
        WHEN regexp_like(p.location, 'Irving') THEN 'Irving'
        WHEN regexp_like(p.location, 'Chesapeake') THEN 'Chesapeake'
        WHEN (regexp_like(p.location, 'Glendale') AND p.state = 'AZ') THEN 'Glendale'
        WHEN regexp_like(p.location, 'Winston-Salem') THEN 'Winston-Salem'
        WHEN regexp_like(p.location, 'Port St.Lucie') THEN 'Port St.Lucie'
        WHEN regexp_like(p.location, 'Scottsdale') THEN 'Scottsdale'
        WHEN regexp_like(p.location, 'Garland') THEN 'Garland'
        WHEN regexp_like(p.location, 'Boise City') THEN 'Boise City'
        WHEN regexp_like(p.location, 'Norfolk') THEN 'Norfolk'
        WHEN regexp_like(p.location, 'Spokane') THEN 'Spokane'
        WHEN regexp_like(p.location, 'Richmond') THEN 'Richmond'
        WHEN regexp_like(p.location, 'Fremont') THEN 'Fremont'
        WHEN regexp_like(p.location, 'Huntsville') THEN 'Huntsville'
        ELSE 'Other'
    END AS city 
    FROM revelio_2022.ai_information_22_25_incl_genderandcity p
),
AI_perc AS (
    SELECT city,
    ROUND (
        (COUNT_IF((title_22_ai = 1 OR desc_22_ai = 1))*100.0)/COUNT(*), 4 
    ) AS AI_cities_22,
    ROUND (
        (COUNT_IF((desc_25_ai = 1 OR title_25_ai = 1))*100.0)/COUNT(*), 4 
    ) AS AI_cities_25
    FROM city_info 
    WHERE city_info.start_year = 2022 AND city_info.city NOT IN ('Other') 
    GROUP BY city_info.city
)
SELECT city, AI_cities_22, AI_cities_25
FROM AI_perc
WHERE AI_perc.AI_cities_22 <> 0.0 AND AI_perc.AI_cities_25 <> 0.0
ORDER BY city